
CREATE TABLE user (
  `id` BIGINT(20) NOT NULL,
  `username` VARCHAR(255) NOT NULL,
  `password` VARCHAR(255) NOT NULL,
  `tenant` VARCHAR(255) NOT NULL,
  `status` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `username_UNIQUE` (`username` ASC));

ALTER TABLE user ALTER COLUMN ID BIGINT(20) NOT NULL AUTO_INCREMENT ;


CREATE TABLE customer (
  `id` BIGINT(20) NOT NULL,
  `name` VARCHAR(255) NOT NULL,
  `address` VARCHAR(255) NULL,
  PRIMARY KEY (`id`));

ALTER TABLE customer ALTER COLUMN ID BIGINT(20) NOT NULL AUTO_INCREMENT ;

